### ISSUE TITLE
Missing pages describing writing and managing a revew

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2-docs#181]
https://www.boost.io/doc/formal-reviews/writing-reviews.html
https://www.boost.io/doc/formal-reviews/managing-reviews.html

These pages are empty.

Until you manage to write something better, just copy the content from the current website:

https://www.boost.org/community/reviews.html

You can omit the Review Wizards section, as that should probably go to the page requested [here](https://github.com/boostorg/website-v2-docs/issues/184).

**Comment by PeterTurcan** [comment]
Andrey,

Thanks for your feedback on the docs. I'll address the issues you raise
that are within my remit shortly.
