### ISSUE TITLE
Typo in Introduction to Boost Formal Reviews

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2-docs#182]
https://www.boost.io/doc/formal-reviews/index.html#_seek_a_review_manager

There's a missing space in "EdwardDiener" in the list.

**Comment by julioest** [comment]
This PR #172 fixes this issue

**Comment by joaquintides** [comment]
Can't merge because of conflicts, don't feel confident to solve them myself.

**Comment by PeterTurcan** [comment]
@joaquintides Maybe just close this PR - I have a big check in of the Formal Review stuff coming and can take care of this issue?

**Comment by joaquintides** [comment]
Closed as per Peter's comment.
