### ISSUE TITLE
New section request: Boost Formal Review Schedule

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2-docs#215]
We'd need to migrate the following page:

https://www.boost.org/community/review_schedule.html

The following archived version probably displays more clearly the different sections this page is made of:

https://web.archive.org/web/20240119182418/https://www.boost.org/community/review_schedule.html

The current page is maintained by @mloskot, the idea would be (if he's ok with it) that he can continue updating the new page, so it'd be advisable to have a simple (and easily extendable) structure.

My proposal is that this section be included in Learn/Boost Formal Reviews.

**Comment by mloskot** [comment]
@joaquintides I'm fine with maintaining the page in the new home. I'm fine with learning the new content management workflow.

**Comment by joaquintides** [comment]
Thank you so much! The new docs are built with AsciiDoc, a sort of Markdown, so it should be a piece of cake for you.

**Comment by PeterTurcan** [comment]
@mloskot Does this work?
https://228.site-docs.prtest2.cppalliance.org/formal-reviews/review-results.html

**Comment by mloskot** [comment]
@PeterTurcan it looks good to me
