### ISSUE TITLE
Contributor/User Guide license footer mentions MPL-2.0 and not BSL 1.0

### ISSUE THREAD

**Issue by Lastique** [boostorg/website-v2-docs#240]
https://www.boost.io/doc/contributor-guide/index.html
https://www.boost.io/doc/user-guide/index.html

At the bottom of the page:

![Screenshot_20240603_003859](https://github.com/boostorg/website-v2-docs/assets/1589747/f0c86bfa-9971-42ec-befb-4fc01beb4b52)

The same footer is present on all nested pages.

I thought the website is licensed under BSL 1.0, is it not?

**Comment by joaquintides** [comment]
> I thought the website is licensed under BSL 1.0, is it not?

Yes, all the content is BSL-licensed. The license note refers to the UI styling component.
