### ISSUE TITLE
Inconsistencies between Learn section highlights and User/Contributor guides

### ISSUE THREAD

**Issue by joaquintides** [boostorg/website-v2-docs#244]
(CCing @PeterTurcan who's the author of the docs). The Learn section has these highlights:

* User Guide
  * Intro to Boost
  * Getting Started
  * Explore the Content
  * FAQ
  * Common Scenarios
  * Advanced Scenarios
  * Library Names & Organization
  * Header & Compiled Binaries
  * Additional Resources
* Contributor Guide
  * Getting Involved
  * Design Guide
  * Version Control
  * Testing
  * Libraries
  * Licenses
  * Portability
  * Code Organization

While the TOCs of the guides is as follows:

* User Guide
  *  Introduction
  * Getting Started
  * Explore the Content
  * FAQ
  * Common Scenarios
  * Advanced Scenarios
  * Community
  * Resources
  * Reference
* Contributor Guide
  * Getting Involved
  * Contributors FAQ
  * Requirements
  * Design Guide
  * Development
  * Build Systems
  * Testing
  * The Super-project
  * Documentation
  * Releases
  * Community

It'd be advisable to bring the Learn section highlights in sync with the guides.

**Comment by PeterTurcan** [comment]
Suggest making the following changes to the Learn page:

**User Guide Learn page:**

1. Remove these two links completely

Library Names & Organization
Header & Compiled Binaries

2. Add the following text and link:
Text:   Introduction to the User Community
Link:   https://www.boost.io/doc/user-guide/user-community-introduction.html

**Contributor Guide Learn page:**

1. Design Guide link is broken - change it to:
https://www.boost.io/doc/contributor-guide/design-guide/design-best-practices.html

2. After "Getting Involved" - add a link to the Contributors FAQ:
Text:   Contributors FAQ
Link:   https://www.boost.io/doc/contributor-guide/contributors-faq.html

3. Add a link to the Super-Project
Text:   The Super-Project
Link:  https://www.boost.io/doc/contributor-guide/superproject/overview.html

4. Change the text from "Libraries" to "Library Requirements" - no other changes to this one

5. Remove the text and links for these (as they are accessed from Library Requirements)
Licenses
Portability
Code Organization

6. Add the text and link:
Text:   Introduction to the Contributors Community
Link:   https://www.boost.io/doc/contributor-guide/contributor-community-introduction.html

These changes should result in both sections containing 8 links into the docs, and be fairly robust going forward.

**Comment by joaquintides** [comment]
Closed, worked continued at https://github.com/boostorg/website-v2/issues/1154.
