### ISSUE TITLE
Modification of Antora UI templates

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2-docs#266]
The antora UI is needing modified to better display the documentation. Below are some mockups. Details to follow.

**With Contents Navigation**
![Screenshot 2024-07-23 at 3 46 42 PM](https://github.com/user-attachments/assets/9132046b-5d56-4c5d-a2ab-ea693c679805)

**Without Contents Navigation**
![Screenshot 2024-07-23 at 3 47 07 PM](https://github.com/user-attachments/assets/d9b33e87-370f-48f7-b5db-31ffa13733a6)

**Specific details:**

1. Insert current website-V2 header to float at top. Keep in mind that it may become fixed to the page in the future. Suggest locking it in place with a specific class that can be removed in the future so it would scroll with the page. Page background will match the header

2. whole page should scroll down.

3. Left side nav - smaller font size and default tree to open. 

4. Contents - Separate from the page to its own area. if a page does not have contents, expand the main page area to fill the space.

5. Main section - the breadcrumb and traditional navigation will be at the top. we won't be using the edit icon next to the breadcrumb. At the bottom of the main section there will also be the traditional navigation and a subtle "edit this page" link

**Comment by julioest** [comment]
@joaquintides Can this be closed?

**Comment by rbbeeston** [comment]
completed
