### ISSUE TITLE
CG: Hide left nav antora config 

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2-docs#270]
We must explain how to configure antora component documentation site to remove the left side navigation.

**Comment by rbbeeston** [comment]
@alandefreitas can you point me in the right direction of what the instructions should look like?

**Comment by alandefreitas** [comment]
> can you point me in the right direction of what the instructions should look like?

I can. But I'm not sure the following is possible:

> We must explain how to configure antora component documentation site to remove the left side navigation.

This is how the option is configured:

https://github.com/boostorg/website-v2-docs/blob/9b1b952d747676b1b7f6b876ed786117c0bae56d/site.playbook.yml#L40
https://github.com/boostorg/website-v2-docs/blob/9b1b952d747676b1b7f6b876ed786117c0bae56d/libs.playbook.yml#L51-L54

The sitedocs and libs playbooks use different configurations. 

It uses the same format as the built-in pagination attribute:

https://docs.antora.org/antora-ui-default/template-customization/#page-pagination-attribute

```yaml
asciidoc:
  attributes:
    page-pagination: ''
```

That is, leaving it undefined disables it and setting it to any string (including the empty string) enables it.

However, this UI option is enabled in the playbook. All components in the playbook will use the same UI with the same options. Thus, enabling or disabling it for a specific component is impossible the way this is set up.

I can look into options to enable or disable it for a specific component, but such a solution would be many orders of magnitude more complex. We would need to create an extension that intervenes with an event listener at some point in the Antora cycle to potentially render the UI with different options for each component.

I don't know if that's possible, but it's much more advanced than any example extension in the Antora documentation. The best way is to ask directly if that's possible on https://antora.zulipchat.com/.

**Comment by alandefreitas** [comment]
@PeterTurcan: when fixing this, the content can just include what I wrote in the previous comment, except for the part about it being impossible to make the change happen for the component, and probably being a little more formal in the language.
