### ISSUE TITLE
CG: Debug Visualizers section

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2-docs#278]
Contributor's Guide needs a section on Debug Visualizers explaining how to use them and write them for MSVC and gdb.

**Comment by joaquintides** [comment]
FWIW, @k3DW has written some documentation on how to write a Natvis visualizer (in the context of Boost.Unordered):

* https://blog.ganets.ky/NatvisForUnordered/
* https://blog.ganets.ky/NatvisForUnordered2/

and is working currently on developing a GDB pretty printer and documenting the process.
