### ISSUE TITLE
CG: Outside Content

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2-docs#289]
The Contributor's Guide needs a section on outside sources for information about Boost, such as:

The Wikipedia page https://en.wikipedia.org/wiki/Boost_(C%2B%2B_libraries)
The LinkedIn page (?)

This section needs to explain the process for reporting when outside sources have out of date information. For example, Boost's Wikipedia entry has old information and needs to be updated. The process is to first open an issue (maybe in website-v2-docs) describing the external source which needs edits.

**Comment by PeterTurcan** [comment]
Linked in page:  https://www.linkedin.com/company/boostlibs/
