### ISSUE TITLE
Change Misc. value in adoc.

### ISSUE THREAD

**Issue by rbbeeston** [boostorg/website-v2-docs#291]
in the intro.adoc on line 79 a bug was introduced in April of 2023 that started breacking the build cycle.

fixes a year old issue that breaks the build.

Will need input as to what the actual value should be. @PeterTurcan originally made the commit, so perhaps he knows what the actual value should be.

In the user-guide/modules/ROOT/pages/intro.adoc line 79 it shows:
`|Miscellaneous | Libraries for numerical type and text conversion, byte ordering, logging, swapping, timing, initialization, and other utilities.`
It should have a number after the first pipe like this, as all the others have them
`|System | 11 | Time utilities, context switching, handling libraries, threads, a smart file system, processes, backtraces, errors.`
I changed the line to
[|Miscellaneous | ? | Libraries for numerical type and text conversion, byte ordering, logging, swapping, timing, initialization, and other utilities.](url)
which solves the problem, but it would be good to add the actual quantity.

**Comment by PeterTurcan** [comment]
This was fixed in this check-in:
https://github.com/boostorg/website-v2-docs/pull/292
- but I got the syntax wrong for the fix 291
