### ISSUE TITLE
antora-ui: Contents panel showing even when turned off

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/website-v2-docs#319]
When the playbook or attributes of an antora documentation site specify no Contents, an empty panel is still shown:

https://860.urlantora.prtest2.cppalliance.org/site/url/reference/boost/urls/authority_view.html

![image](https://github.com/user-attachments/assets/a0542252-1c0c-4255-9feb-3630a81c2c0f)

**Comment by alandefreitas** [comment]
In which playbooks (sitedocs / libs) should we enable/disable the contents panel?

**Comment by vinniefalco** [comment]
I don't like Contents anywhere. If a Boost library author wants to turn it on for their Antora-based documentation, then they may do so.

**Comment by alandefreitas** [comment]
> then they may do so.

That's why I ask. They may not. There's no mechanism to replace the UI bundle or UI bundle parameters for a single component.

**Comment by vinniefalco** [comment]
Sorry, I'm not being clear. What I mean is this: if there is a strong desire by other authors to have the Contents panel in their Antora documentation, then we should bring it back but with a way to configure it on or off, defaulting to off. For now I want to just rip it out and never see it again.
