### ISSUE TITLE
Fetch boostlook.css from the correct branch (master or develop)

### ISSUE THREAD

**Issue by julioest** [boostorg/website-v2-docs#332]
The `fetchBoostlookCss` function currently always downloads boostlook.css from the master branch, regardless of which branch is being built. This can lead to inconsistencies when building from the develop branch, as the styles may not match the codebase.

We need to update the function to dynamically determine the current Git branch (master or develop) and fetch boostlook.css from the corresponding branch in the boostlook repository. This will ensure consistency between the code and styles across different branches.

reference https://github.com/boostorg/website-v2-docs/pull/331#issuecomment-2349947114

**Comment by alandefreitas** [comment]
Do you have any suggestions on how this should be implemented? The gulp task finds and runs git to identify the current branch? Or would it be another command line option to set what branch of boostlook we want?

**Comment by alandefreitas** [comment]
> Or would it be another command line option to set what branch of boostlook we want?

That's the correct solution because you are concerned about the preview to AWS and the website. So, the build task can have the option to choose the branch, and we would choose to develop or master accordingly in CI before the automation uploads it to AWS.

**Comment by alandefreitas** [comment]
resolved: https://github.com/boostorg/website-v2-docs/pull/335

I'm sorry I forgot to tag the issue on the commit
