### ISSUE TITLE
Fix issues with mobile Table of Contents nav

### ISSUE THREAD

**Issue by cdw9** [boostorg/website-v2-docs#362]
I'm seeing a few issues related to the TOC on mobile:
* At https://www.boost.io/doc/libs/develop/doc/antora/url/index.html in a mobile browser, opening the TOC hides the content, but doesn't show the navigation
* At the same location in a narrow  desktop browser, the menu has a couple bars of extra space above it: 
<img src="https://github.com/user-attachments/assets/e1a40530-7593-4e45-b4ae-2f630a79edbb" width=300 />

* If I look at the Antora UI locally in a mobile browser or narrow desktop browser, there is a bunch of blank space at the top of the page. The space is caused by the TOC
<img src="https://github.com/user-attachments/assets/d2c479c9-0099-406d-a518-83d1e2675061" width=200 />

**Comment by rbbeeston** [comment]
@julioest can you take a look at this and see if it's a boostlook type issue, or due to the iframe things we discussed. See if it should be fixed by you or Dave and reassign if needed. Thanks!

And thank you Chrissy for catching it and making a ticket!

**Comment by julioest** [comment]
This has been fixed previously in Issue https://github.com/boostorg/website-v2-docs/issues/359

<img src="https://github.com/user-attachments/assets/2efca6e9-c91a-4c0f-87ee-27d235c2bfed" width="40%" >
